// export const trainingData = [
//     {
//         id: 1,
//         imageSrc: "/person1.jpg",
//         imageAlt: "Person 1",
//         number: "01",
//         category: "Individuals",
//         count: "100 +",
//         title: "We train individuals for careers in digital marketing.",
//         description: "We equip individuals with the comprehensive skills and up-to-date knowledge needed to thrive in the fast-paced world of digital marketing. Our training programs are designed to prepare you for a successful career, offering hands-on experience and expert guidance in key areas such as SEO, social media, content marketing, and analytics. Whether you’re looking to start a new career or enhance your existing skills, we provide the tools and support to help you achieve your goals in the digital marketing industry.",
//         buttonText: "Contact Us",
//     },
//     {
//         id: 2,
//         imageSrc: "/person2.jpg",
//         imageAlt: "Person 2",
//         number: "02",
//         category: "Entrepreneurs",
//         count: "100 +",
//         title: "We Train Entrepreneurs for a successful Business launch.",
//         description: "We provide entrepreneurs with the essential tools, strategies, and support needed to launch their businesses successfully. From initial concept development to market analysis, our comprehensive programs ensure that you start your entrepreneurial journey with a solid foundation. Whether you're starting a new venture or refining long-term strategies in a competitive market, we provide the guidance and tailored solutions you need.",
//         buttonText: "Contact Us",
//     },
//     {
//         id: 3,
//         imageSrc: "/person3.jpg",
//         imageAlt: "Person 3",
//         number: "03",
//         category: "Companies",
//         count: "100 +",
//         title: "We train Company teams for rapid expansion.",
//         description: "We support company teams in driving rapid and sustainable business expansion through targeted planning, expert guidance, and targeted execution strategies. Our training programs are designed to foster scalable business growth by streamlining processes and capitalizing on growth opportunities.",
//         buttonText: "Contact Us",
//     },
//     {
//         id: 4,
//         imageSrc: "/person4.webp",
//         imageAlt: "Person 4",
//         number: "04",
//         category: "Consultancy",
//         count: "100 +",
//         title: "We provide Digital Marketing Consultancy.",
//         description: "We offer expert digital marketing consultancy services to help businesses navigate the complexities of the online marketplace. Our consultants work closely with you to develop tailored strategies that align with your goals, ensuring that your brand presence is strong and effective in the digital landscape.",
//         buttonText: "Contact Us",
//     },
// ];